##**NUMPY BASICS**

CREATING A NUMPY ARRAY AND ITS ATTRIBUTES

In [ ]:
# #importing numpy library
# import numpy as np
# #creating a list
# my_list=[1,2,3,4,5]
# #changing thr list into a 1-D numpy array
# my_array=np.array(my_list)
# #printing thr array
# print(my_array)

# #creating 0-D numpy array
# zero_array=np.array(42)
# #printing thr 0-D numpy array
# print(zero_array)

# #instead of creating a list on a seperate variable we can directly passs that list to .array() function like this:
# my_array=np.array([1,2,3,4,5])
# #printing the 1-D numpy array
# print(my_array)


# #lets create a 2-D array!
# two_d_array=np.array([[1,2,3],
#                      [4,5,6]])
# #printing the 2-D numpy array
# print(two_d_array)


#lets create 3-D array
three_d_array=np.array([[[1,2,3],
                     [4,5,6]],
                        [[7,8,9],
                        [10,11,12]]])
#printing the 2-D numpy array
print(three_d_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#lets create an array and see its attribute
my_array=np.array([[1,2,3],[4,5,6]])
print(my_array)#print array
print(my_array.ndim)#print array dimension
print(my_array.shape)#print the array shape
print(my_array.dtype)#print array type
print(my_array.size)#print array size

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64
6


ACCESSING SND MANIPULATING ARRAY ELEMENTS

In [ ]:
#lets create a 1-D array and print one of its elemets
one_arr=np.array([1,2,3,4,5,6])
print(one_arr[4])

#lets print using negative indexing
print(one_arr[-3])

5
4


In [ ]:
#lets do for two D array
two_arr=np.array([[1,2,3],
                  [4,5,6]])
print(two_arr[0,2])

3


In [ ]:
#lets move to s 3_D srray
three_arr=np.array([[[1,2,3],[4,5,6]],   [[7,8,9],[10,11,12]]])
print(three_arr)
print(three_arr[1,0,0])
print(three_arr[0,0,2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
7
3


NEGATIVE INDEXING

In [ ]:
three_arr=np.array([[[1,2,3],[4,5,6]],   [[7,8,9],[10,11,12]]])
print(three_arr[-1,-2,-3])

7


SLICING ARRAY


In [ ]:
# important slicing concepts
# array[start:end]
# array[start:end:steps]

#SLICING ARRAY FROM 0TH INDEX TO 8TH INDEX
my_array =np.array([1,2,3,4,5,6,7,8,9,10])
print(my_array[0:8])



[1 2 3 4 5 6 7 8]


In [ ]:
#slicing with steps
my_new_array=np.array([1,2,3,4,5,6,7,8,9,10])
print(my_new_array[0:9:2])

[1 3 5 7 9]


In [ ]:
# slicing with two D array
my_two_d=np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])
print(my_two_d[1,0:6])

[10 11 12 13 14 15]


In [ ]:
# slicing with steps for two D array
my_two_d=np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])
print(my_two_d[0,3:6])

[4 5 6]


In [ ]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

#**CLASSWORK**

In [ ]:
#create a numpy array from list
alist=[7,14,21,28]
print(np.array(alist))

[ 7 14 21 28]


In [ ]:
#printing two D arrays shape and dimension number
two_array=np.array([[5,10,15],[20,25,30]])
print("The shape of array is",two_array.shape)
print("The dimension of array is",two_array.ndim)

The shape of array is (2, 3)
The dimension of array is 2


In [ ]:
#creating zeros array and using .arange(0,12) with step 3
zer=np.zeros([2,3])
print(zer)

arr= np.arange(0,12,3)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[0 3 6 9]


In [ ]:
#creating array and multiplying by 3
arr=np.array([2,4,6,8])
print(arr*3)

[ 6 12 18 24]


In [ ]:
#creating array and printing third element and slicing from 1 to 3
arr=np.array([1,3,5,7,9])
print(arr[3])
print(arr[1:3])

7
[3 5]


#**INTERMEDIATE NUMPY QUESTION**

In [94]:
arr=np.random.randint(1,10,(3,3))
arr[arr>5]=0
print(arr)

[[3 0 3]
 [2 4 0]
 [0 0 3]]


In [86]:

#sum and multiplication of two array
arr1=np.array([2,4,6,8])
arr2=np.array([1,3,5,7])
print(np.dot(arr1,arr2))
print(arr1+arr2)

100
[ 3  7 11 15]


In [ ]:
one=np.ones([4,3])
add=np.array([10,20,30])
print(one+add)

[[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]


In [87]:
#extractiong second colum and taking mean of its

Arr=np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])
marr=Arr[ :,1]
print(marr)
print(np.mean(marr))

[2 5 8]
5.0


In [97]:


#using boolen masking to get element greater tha 30
arr = np.array([10, 20, 30, 40, 50, 60])

# Create a boolean mask for elements greater than 3
mask = arr > 30

# Apply the mask to filter the array
filtered_arr = arr[mask]
sqr_arr=np.square(filtered_arr)
print(f"Squared array: {sqr_arr}")
print(f"Filtered array: {filtered_arr}")

Squared array: [1600 2500 3600]
Filtered array: [40 50 60]
